Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Enabled: false
AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"